/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  Implementation3,
  Implementation3Interface,
} from "../Implementation3";

const _abi = [
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610252806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630ff4c9161461004657806355241077146100885780638129fc1c146100b6575b600080fd5b6100726004803603602081101561005c57600080fd5b81019080803590602001909291905050506100c0565b6040518082815260200191505060405180910390f35b6100b46004803603602081101561009e57600080fd5b81019080803590602001909291905050506100ce565b005b6100be6100d8565b005b600081600154019050919050565b8060018190555050565b600060019054906101000a900460ff16806100f757506100f66101d7565b5b8061010e57506000809054906101000a900460ff16155b610163576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001806101ef602e913960400191505060405180910390fd5b60008060019054906101000a900460ff1615905080156101b3576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b80156101d45760008060016101000a81548160ff0219169083151502179055505b50565b6000803090506000813b905060008114925050509056fe496e697469616c697a61626c653a20636f6e747261637420697320616c726561647920696e697469616c697a6564a2646970667358221220acf0b20f48c6523cdba63619c95dc56324ce70cdbfee95c6cc144f814a4019e164736f6c63430006020033";

type Implementation3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation3__factory extends ContractFactory {
  constructor(...args: Implementation3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "Implementation3";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Implementation3> {
    return super.deploy(overrides || {}) as Promise<Implementation3>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Implementation3 {
    return super.attach(address) as Implementation3;
  }
  connect(signer: Signer): Implementation3__factory {
    return super.connect(signer) as Implementation3__factory;
  }
  static readonly contractName: "Implementation3";
  public readonly contractName: "Implementation3";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation3Interface {
    return new utils.Interface(_abi) as Implementation3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Implementation3 {
    return new Contract(address, _abi, signerOrProvider) as Implementation3;
  }
}
