/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Building, BuildingInterface } from "../Building";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "isLastFloor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Building__factory {
  static readonly abi = _abi;
  static createInterface(): BuildingInterface {
    return new utils.Interface(_abi) as BuildingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Building {
    return new Contract(address, _abi, signerOrProvider) as Building;
  }
}
