/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  EtherReceiverMock,
  EtherReceiverMockInterface,
} from "../EtherReceiverMock";

const _abi = [
  {
    stateMutability: "payable",
    type: "receive",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "acceptEther",
        type: "bool",
      },
    ],
    name: "setAcceptEther",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060cc8061001f6000396000f3fe608060405260043610601f5760003560e01c80634fea120c14604157603c565b36603c576000809054906101000a900460ff16603a57600080fd5b005b600080fd5b348015604c57600080fd5b50607860048036036020811015606157600080fd5b81019080803515159060200190929190505050607a565b005b806000806101000a81548160ff0219169083151502179055505056fea2646970667358221220a71669081456b0f75e94ad2bb178b518d355b036789b2e77ad2907e43b2fa6fc64736f6c63430006020033";

type EtherReceiverMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EtherReceiverMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EtherReceiverMock__factory extends ContractFactory {
  constructor(...args: EtherReceiverMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "EtherReceiverMock";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EtherReceiverMock> {
    return super.deploy(overrides || {}) as Promise<EtherReceiverMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EtherReceiverMock {
    return super.attach(address) as EtherReceiverMock;
  }
  connect(signer: Signer): EtherReceiverMock__factory {
    return super.connect(signer) as EtherReceiverMock__factory;
  }
  static readonly contractName: "EtherReceiverMock";
  public readonly contractName: "EtherReceiverMock";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EtherReceiverMockInterface {
    return new utils.Interface(_abi) as EtherReceiverMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EtherReceiverMock {
    return new Contract(address, _abi, signerOrProvider) as EtherReceiverMock;
  }
}
