/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { SampleHuman, SampleHumanInterface } from "../SampleHuman";

const _abi = [
  {
    inputs: [],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061020f806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80634a6c9db61461003b5780638129fc1c1461005d575b600080fd5b610043610067565b604051808215151515815260200191505060405180910390f35b61006561007a565b005b600060029054906101000a900460ff1681565b600060019054906101000a900460ff16806100995750610098610194565b5b806100b057506000809054906101000a900460ff16155b610105576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001806101ac602e913960400191505060405180910390fd5b60008060019054906101000a900460ff161590508015610155576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b6001600060026101000a81548160ff02191690831515021790555080156101915760008060016101000a81548160ff0219169083151502179055505b50565b6000803090506000813b905060008114925050509056fe496e697469616c697a61626c653a20636f6e747261637420697320616c726561647920696e697469616c697a6564a2646970667358221220a575b468489f2d6476c0a7fb5426a2f3440c729ccc87eeaba427c562c77106ba64736f6c63430006020033";

type SampleHumanConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SampleHumanConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SampleHuman__factory extends ContractFactory {
  constructor(...args: SampleHumanConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "SampleHuman";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SampleHuman> {
    return super.deploy(overrides || {}) as Promise<SampleHuman>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SampleHuman {
    return super.attach(address) as SampleHuman;
  }
  connect(signer: Signer): SampleHuman__factory {
    return super.connect(signer) as SampleHuman__factory;
  }
  static readonly contractName: "SampleHuman";
  public readonly contractName: "SampleHuman";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SampleHumanInterface {
    return new utils.Interface(_abi) as SampleHumanInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SampleHuman {
    return new Contract(address, _abi, signerOrProvider) as SampleHuman;
  }
}
