/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { SampleMother, SampleMotherInterface } from "../SampleMother";

const _abi = [
  {
    inputs: [],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "mother",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610386806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80634a6c9db6146100515780638129fc1c14610073578063ed7dfee31461007d578063fe4b84df1461009b575b600080fd5b6100596100c9565b604051808215151515815260200191505060405180910390f35b61007b6100dc565b005b6100856101f6565b6040518082815260200191505060405180910390f35b6100c7600480360360208110156100b157600080fd5b81019080803590602001909291905050506101fc565b005b600060029054906101000a900460ff1681565b600060019054906101000a900460ff16806100fb57506100fa61030b565b5b8061011257506000809054906101000a900460ff16155b610167576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e815260200180610323602e913960400191505060405180910390fd5b60008060019054906101000a900460ff1615905080156101b7576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b6001600060026101000a81548160ff02191690831515021790555080156101f35760008060016101000a81548160ff0219169083151502179055505b50565b60015481565b600060019054906101000a900460ff168061021b575061021a61030b565b5b8061023257506000809054906101000a900460ff16155b610287576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e815260200180610323602e913960400191505060405180910390fd5b60008060019054906101000a900460ff1615905080156102d7576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b6102df6100dc565b8160018190555080156103075760008060016101000a81548160ff0219169083151502179055505b5050565b6000803090506000813b905060008114925050509056fe496e697469616c697a61626c653a20636f6e747261637420697320616c726561647920696e697469616c697a6564a264697066735822122013a9bfc8dd9a8c509b083a7472453931c6f497eb2d836f095acc93c3950178ad64736f6c63430006020033";

type SampleMotherConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SampleMotherConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SampleMother__factory extends ContractFactory {
  constructor(...args: SampleMotherConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "SampleMother";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SampleMother> {
    return super.deploy(overrides || {}) as Promise<SampleMother>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SampleMother {
    return super.attach(address) as SampleMother;
  }
  connect(signer: Signer): SampleMother__factory {
    return super.connect(signer) as SampleMother__factory;
  }
  static readonly contractName: "SampleMother";
  public readonly contractName: "SampleMother";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SampleMotherInterface {
    return new utils.Interface(_abi) as SampleMotherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SampleMother {
    return new Contract(address, _abi, signerOrProvider) as SampleMother;
  }
}
