/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AttackInterface extends utils.Interface {
  contractName: "Attack";
  functions: {
    "owner()": FunctionFragment;
    "timeZone1Library()": FunctionFragment;
    "timeZone2Library()": FunctionFragment;
    "attack(address)": FunctionFragment;
    "setTime(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timeZone1Library",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeZone2Library",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "attack", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setTime",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timeZone1Library",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeZone2Library",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setTime", data: BytesLike): Result;

  events: {};
}

export interface Attack extends BaseContract {
  contractName: "Attack";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AttackInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    owner(overrides?: CallOverrides): Promise<[string]>;

    timeZone1Library(overrides?: CallOverrides): Promise<[string]>;

    timeZone2Library(overrides?: CallOverrides): Promise<[string]>;

    attack(
      p: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTime(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  timeZone1Library(overrides?: CallOverrides): Promise<string>;

  timeZone2Library(overrides?: CallOverrides): Promise<string>;

  attack(
    p: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTime(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    timeZone1Library(overrides?: CallOverrides): Promise<string>;

    timeZone2Library(overrides?: CallOverrides): Promise<string>;

    attack(p: string, overrides?: CallOverrides): Promise<void>;

    setTime(arg0: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    timeZone1Library(overrides?: CallOverrides): Promise<BigNumber>;

    timeZone2Library(overrides?: CallOverrides): Promise<BigNumber>;

    attack(
      p: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTime(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timeZone1Library(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timeZone2Library(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    attack(
      p: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTime(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
